# frozen_string_literal: true

require_relative './position'
require_relative './null_position'
require_relative './square'
require_relative './board'
require_relative './fen'
require_relative './piece'
require_relative './null_piece'
require_relative './rules'
require_relative './move'
require_relative './bishop'
require_relative './rook'
require_relative './knight'
require_relative './queen'
require_relative './king'
require_relative './pawn'
require_relative './army'
require_relative './evaluation'